### ISSUE TITLE
some thing wrong about the data of polaris_sensor

### ISSUE THREAD

**Issue by RLoad** [kuka-isir/polaris_sensor#3]
Hello! Your ROS package is really great and very convenient to use, while i have found a problem when i try to get data using your package. The time stamp of data is changed one by one, while data didn't change until record three or four same data. So the data is not a curve but more like a square wave, and can't use in my experiment... so, how can i change this to make one time stamp corresponding to one data?

**Comment by ahoarau** [comment]
Hi! I haven't worked on this in 4 years + no access to the sensor anymore.
Looking at the code, I sea that it waits until new data is available on the serial port before going any further (https://github.com/kuka-isir/polaris_sensor/blob/master/src/polaris_ros.cpp#L103), and the timeout should be infinite (https://github.com/kuka-isir/polaris_sensor/blob/master/src/polaris_sensor.cpp#L114).
Maybe you could check if timeout=0 actually means infinite wait. And also check your sensor configuration. There might be a missing option somewhere.

**Comment by RLoad** [comment]
Thank you for your help! I try to change the timeout and find out it will not change the result so I think it not the reason. Then I found in my sensor configuration, the Frame Frequency is 60Hz while the Illuminator Rate is 20 Hz. Change the Illuminator Rate to 60Hz can make the data speed up data acquisition. So I think maybe this is the reason why I get three same data with different time stamp. So thank you for your advise!
Now I‘m trying to change the sensor config in linux, but it may take some time because I'm not so fimiliar with the NDI API programming. So any advise is valuable for me! Thanks for you help again!

**Comment by ahoarau** [comment]
As far as I remember, it had a Windows configuration. Did you try that ?

**Comment by RLoad** [comment]
Yes, it has and I have try it. Yesterday I try to change the sensor illuminator in Windows configuration, while each time I re-open any application such as Track or re-run your code, the sensor will re-configure by it self with two beep. It seems that the configuration can only be changed once in a single application and cannot be permanently modified and used in other application.

**Comment by ahoarau** [comment]
I guess you know better than me now, so I'm closing the issue.

**Comment by RLoad** [comment]
Thanks for your help, I find the "SET" commend in API can directly change the illuminator rate in your code, This commend can be call just like the call the "INIT" commend in your polaris_sensor.cpp! Problem solved! Thanks again!
